#include <avr/io.h>
#include "uart.h"
#include "i2c_status_msg.h"

#ifndef F_CPU
 #define F_CPU		16000000UL
#endif

#define AHT20_ADDR	0x38 // AHT20 Data Sheet, Version:V1.0, p.12
#define STATUS_MSK	0xF8 // DS40002061B-p.240 (cf. TWS7..TWS3 bit positions)

void i2c_init(void)
{

	// Enable internal pull-up resistor for PC4/SDA and PC5/SCL (not strictally necessary because pull-up R6 and R7 in the PCB, but good practice)
	PORTC |= (1 << PORTC4) | (1 << PORTC5); // DS40002061B-page 221 the internal pull-ups in the AVR pads can be enabled by setting the PORT
	// bits corresponding to the SCL and SDA pins, as explained in the I/O Port section.
	// The internal pull-ups can in some systems eliminate the need for external ones.

	// Enable the TWI module
	PRR &= ~(1 << PRTWI); // DS40002061B-p.54 & p.216 PRTWI bit must be written to zero to enable the 2-wire Serial Interface.
	// p.54 Writing a logic one to this bit shuts down the TWI by stopping the clock to the module. When waking up the TWI
	// again, the TWI should be re initialized to ensure proper operation.

	// Set the TWI bit rate for 100 kHz SCL frequency
	// DS40002061B-p.222 + 240
	// Formula: SCL_freq = F_CPU / (16 + 2 * TWBR * PrescalerValue)
	// For 100 kHz with F_CPU = 16 MHz and prescaler = 1:
	// TWBR: Value of the TWI Bit Rate Register (0-255)
	// PrescalerValue: Value of the prescaler (1, 4, 16, or 64)
	// 100,000 = 16,000,000 / (16 + 2 * TWBR * 1) => TWBR = 72
	TWBR = 72;  // For 100 kHz SCL frequency
	// TWSR = 0;   // Clear/Reset status register (5 bits status) + Clear prescaler bits (prescaler = 1) => reinitialize the TWI module
	TWSR &= ~(1 << TWPS1); // DS40002061B-p.240 Set TWI Bit Rate Prescaler = 1
	TWSR &= ~(1 << TWPS0);

	// Enable TWI
	TWCR = (1 << TWEN); // DS40002061B-p.240 TWI takes control over the I/O pins connected to the SCL and SDA pins
}

void i2c_start(void)
{
	// DS40002061B-page 226 and 227

	// Send START condition
	// DS40002061B-page 226 A START condition is sent by writing the following value to TWCR
	TWCR = (1 << TWINT) | (1 << TWEN) | (1 << TWSTA); // Clear TWINT, enable TWI, and send START
	// => Clear any previous TWI Interrupt Flag and start operation of the TWI
	// "TWCR = (1 << TWINT) // DS40002061B-p.239 Clearing this flag starts the operation of the TWI, so all accesses to the TWI Address Register (TWAR), TWI Status Register (TWSR), and TWI Data Register (TWDR) must be complete before clearing this flag.
	// => Send START condition
	// - Set TWSTA bit to one when it desires to become a Master
	// - TWI hardware checks if the bus is available, and generates a START condition on the bus if it is free
	// "TWCR = (1 << TWSTA)" // DS40002061B-p.240
	// => Enable TWI
	// "TWCR = (1 << TWEN)" // DS40002061B-p.240 TWI takes control over the I/O pins connected to the SCL and SDA pins
	
	// Wait for TWINT flag to be set (confirm START transmitted by hardware logic)
	while (!(TWCR & (1 << TWINT))) // DS40002061B-p.222 The TWINT Flag is set after the TWI has transmitted a START/REPEATED START condition.
	{}

	// Display feedback status after START
	uart_display_status(TWSR & STATUS_MSK); // DS40002061B-p.222 When an event requiring the attention of the application occurs on the TWI bus, the TWI
	// Interrupt Flag (TWINT) is asserted. In the next clock cycle, the TWI Status Register (TWSR) is updated with a
	// status code identifying the event. The TWSR only contains relevant status information when the TWI Interrupt
	// Flag is asserted. 

	// Load address + write bit into TWDR
	// => I2C Bus Specification (UM10204)
	// - Bits 7-1: 7-bit slave address
	// - Bit 0: R/W bit (0 = write, 1 = read)
	TWDR = (AHT20_ADDR << 1) & ~(1 << 0); // UM10204-Rev.7.0-p.13 Target address and R/W bit

	// Clear TWINT to send address/SLA+W
	// DS40002061B-p.227  This is done by writing SLA+W to TWDR.
	// TWINT bit should be cleared (by writing it to one) to continue the transfer.
	// This is accomplished by writing the following value to TWCR:
	TWCR = (1 << TWINT) | (1 << TWEN);

	// Wait for TWINT to see if addrees/SLA+W was sent and ACK received
	while (!(TWCR & (1 << TWINT))) // DS40002061B-p.222 The TWINT Flag is set after the TWI has transmitted SLA+R/W.
	{}

	// Display feedback status after address transmission
	uart_display_status(TWSR & STATUS_MSK); // DS40002061B-p.222
}

void i2c_stop(void)
{
	// Send STOP condition
	// DS40002061B-p.227 STOP condition is generated by writing the following value to TWCR:
	TWCR = (1 << TWINT) |(1 << TWEN) | (1 << TWSTO);

	// Wait for STOP to be executed (TWSTO is cleared automatically by hardware)
	while (TWCR & (1 << TWSTO)) // DS40002061B-p.227 STOP condition will be transmitted and TWSTO Flag will be reset
	{}
}

int main(void)
{
	uart_init();
	uart_printstr("UART Initialized\r\n");
	i2c_init();
	uart_printstr("I2C Initialized\r\n");
	i2c_start();
	uart_printstr("I2C START Sent\r\n");
	i2c_stop();
	uart_printstr("I2C STOP Sent\r\n");
	while (1)
	{}
}

// DS40002061B-page 221
// Figure 22-9. Overview of the TWI Module

// START and STOP Conditions (p.217)
// The Master initiates and terminates a data transmission. The transmission is initiated when the Master issues a
// START condition on the bus, and it is terminated when the Master issues a STOP condition. Between a START
// and a STOP condition, the bus is considered busy, and no other master should try to seize control of the bus
// START and STOP conditions are signalled by changing the level of the SDA line when the SCL line is high.

// REPEATED START condition (p.217)
// It is used when the Master wishes to initiate a new transfer without relinquishing control of the b

// Address Packet Format (p.217)
// All address packets transmitted on the TWI bus are 9 bits long, consisting of 7 address bits, one READ/WRITE
// control bit and an acknowledge bit. If the READ/WRITE bit is set, a read operation is to be performed, otherwise
// a write operation should be performed.

// Data Packet Format (p.218)
// All data packets transmitted on the TWI bus are nine bits long, consisting of one data byte and an acknowledge
// bit. During a data transfer, the Master generates the clock and the START and STOP conditions, while the
// Receiver is responsible for acknowledging the reception. An Acknowledge (ACK) is signalled by the Receiver
// pulling the SDA line low during the ninth SCL cycle. 

// Why Are Pull-Up Resistors Needed?
// Open-Drain Logic
// I2C devices use open-drain outputs for SDA and SCL.
// This means they can pull the line to GND (LOW) but cannot drive it to VCC (HIGH).
// Without pull-up resistors, the lines would float when no device is pulling them low, leading to undefined logic levels.
// Pull-Up Resistors Provide:
// A default HIGH state for the bus when no device is actively pulling it low.
// A way for devices to share the bus without conflicts (wired-AND logic).
// => If any device pulls the line low, the line is LOW.
// => If no device pulls the line low, the pull-up resistor pulls it HIGH.

// DS40002061B-page 317
// Table 29-14. Two-wire Serial Bus Requirements
// Symbol	Parameter				Condition						Min.		Max.		Units
// VIL		Input Low-voltage 										-0.5 		0.3 VCC		V
// VIH		Input High-voltage 										0.7 VCC		VCC + 0.5	V
// F_SCL	SCL Clock Frequency		F_CPU > max(16 F_SCL, 250kHz)	0			400			kHz
