#include <avr/io.h>
#include "uart.h"
#include "i2c_status_msg.h"
#include "delay_us_and_ms.h"

#ifndef F_CPU
 #define F_CPU		16000000UL
#endif

#define AHT20_ADDR	0x38 // AHT20 Data Sheet, Version:V1.0, p.12
#define AHT20_MEASUREMENT_CMD	0xAC // AHT20 Data Sheet, Version:V1.0, p.12 / Normal Command
#define AHT20_STATUS_WORD		0x18 // AHT20 Data Sheet, Version:V1.0, p.12 
#define AHT20_STATUS_WORD_RQST	0x71 // AHT20 Data Sheet, Version:V1.0, p.12
#define AHT20_STATUS_BUSY (1 << 7)
#define STATUS_MSK	0xF8 // DS40002061B-p.240 (cf. TWS7..TWS3 bit positions)

typedef struct s_measurement
{
	float	temperature;
	float	humidity;
}	t_measurement;

t_measurement	g_measurements[3] = {0};
uint8_t			g_measurement_index = 0;

float round_to_ten(float value)
{
	return (float)((int)(value / 10.0 + 0.5)) * 10.0;
}

float round_to_one(float value)
{
	return (float)((int)(value + 0.5));
}

float round_to_tenth(float value)
{
	return (float)((int)(value * 10.0 + 0.5)) / 10.0;
}

void calculate_average(float *avg_temp, float *avg_humidity)
{
	float temp_sum = 0;
	float hum_sum = 0;

	for (uint8_t i = 0; i < 3; i++)
	{
		temp_sum += g_measurements[i].temperature;
		hum_sum += g_measurements[i].humidity;
	}

	*avg_temp = temp_sum / 3;
	*avg_humidity = hum_sum / 3;
}

void i2c_init(void)
{

	// Enable internal pull-up resistor for PC4/SDA and PC5/SCL (not strictally necessary because pull-up R6 and R7 in the PCB, but good practice)
	PORTC |= (1 << PORTC4) | (1 << PORTC5); // DS40002061B-page 221 the internal pull-ups in the AVR pads can be enabled by setting the PORT
	// bits corresponding to the SCL and SDA pins, as explained in the I/O Port section.
	// The internal pull-ups can in some systems eliminate the need for external ones.

	// Enable the TWI module
	PRR &= ~(1 << PRTWI); // DS40002061B-p.54 & p.216 PRTWI bit must be written to zero to enable the 2-wire Serial Interface.
	// p.54 Writing a logic one to this bit shuts down the TWI by stopping the clock to the module. When waking up the TWI
	// again, the TWI should be re initialized to ensure proper operation.

	// Set the TWI bit rate for 100 kHz SCL frequency
	// DS40002061B-p.222 + 240
	// Formula: SCL_freq = F_CPU / (16 + 2 * TWBR * PrescalerValue)
	// For 100 kHz with F_CPU = 16 MHz and prescaler = 1:
	// TWBR: Value of the TWI Bit Rate Register (0-255)
	// PrescalerValue: Value of the prescaler (1, 4, 16, or 64)
	// 100,000 = 16,000,000 / (16 + 2 * TWBR * 1) => TWBR = 72
	TWBR = 72;  // For 100 kHz SCL frequency
	// TWSR = 0;   // Clear/Reset status register (5 bits status) + Clear prescaler bits (prescaler = 1) => reinitialize the TWI module
	TWSR &= ~(1 << TWPS1); // DS40002061B-p.240 Set TWI Bit Rate Prescaler = 1
	TWSR &= ~(1 << TWPS0);

	// Enable TWI
	TWCR = (1 << TWEN); // DS40002061B-p.240 TWI takes control over the I/O pins connected to the SCL and SDA pins
}

void i2c_start(void)
{
	// DS40002061B-page 226 and 227

	// Send START condition
	// DS40002061B-page 226 A START condition is sent by writing the following value to TWCR
	TWCR = (1 << TWINT) | (1 << TWEN) | (1 << TWSTA); // Clear TWINT, enable TWI, and send START
	// => Clear any previous TWI Interrupt Flag and start operation of the TWI
	// "TWCR = (1 << TWINT) // DS40002061B-p.239 Clearing this flag starts the operation of the TWI, so all accesses to the TWI Address Register (TWAR), TWI Status Register (TWSR), and TWI Data Register (TWDR) must be complete before clearing this flag.
	// => Send START condition
	// - Set TWSTA bit to one when it desires to become a Master
	// - TWI hardware checks if the bus is available, and generates a START condition on the bus if it is free
	// "TWCR = (1 << TWSTA)" // DS40002061B-p.240
	// => Enable TWI
	// "TWCR = (1 << TWEN)" // DS40002061B-p.240 TWI takes control over the I/O pins connected to the SCL and SDA pins
	
	// Wait for TWINT flag to be set (confirm START transmitted by hardware logic)
	while (!(TWCR & (1 << TWINT))) // DS40002061B-p.222 The TWINT Flag is set after the TWI has transmitted a START/REPEATED START condition.
	{}

	// // Display feedback status after START
	// uart_display_status(TWSR & STATUS_MSK); // DS40002061B-p.222 When an event requiring the attention of the application occurs on the TWI bus, the TWI
	// // Interrupt Flag (TWINT) is asserted. In the next clock cycle, the TWI Status Register (TWSR) is updated with a
	// // status code identifying the event. The TWSR only contains relevant status information when the TWI Interrupt
	// // Flag is asserted. 
}

void i2c_stop(void)
{
	// Send STOP condition
	// DS40002061B-p.227 STOP condition is generated by writing the following value to TWCR:
	TWCR = (1 << TWINT) |(1 << TWEN) | (1 << TWSTO);

	// Wait for STOP to be executed (TWSTO is cleared automatically by hardware)
	while (TWCR & (1 << TWSTO)) // DS40002061B-p.227 STOP condition will be transmitted and TWSTO Flag will be reset
	{}
}

void i2c_send_address(uint8_t address, uint8_t read)
{
	// Load address + write bit into TWDR
	// => I2C Bus Specification (UM10204)
	// - Bits 7-1: 7-bit slave address
	// - Bit 0: R/W bit (0 = write, 1 = read)
	if (read == 0) 
		TWDR = (address << 1) & ~(1 << 0); // UM10204-Rev.7.0-p.13 Target address and R/W bit
	else
		TWDR = (address << 1) | (1 << 0);

	// Clear TWINT to send address/SLA+W
	// DS40002061B-p.227  This is done by writing SLA+W to TWDR.
	// TWINT bit should be cleared (by writing it to one) to continue the transfer.
	// This is accomplished by writing the following value to TWCR:
	TWCR = (1 << TWINT) | (1 << TWEN);

	// Wait for TWINT to see if addrees/SLA+W was sent and ACK received
	while (!(TWCR & (1 << TWINT))) // DS40002061B-p.222 The TWINT Flag is set after the TWI has transmitted SLA+R/W.
	{}

	// // Display feedback status after address transmission
	// uart_display_status(TWSR & STATUS_MSK); // DS40002061B-p.222
}

void i2c_write(unsigned char data)
{
	// Load data into TWDR
	TWDR = data;

	// Clear TWINT to send TWDR
	TWCR = (1 << TWINT) | (1 << TWEN);

	// Wait for TWINT to see if data was sent and ACK received
	while (!(TWCR & (1 << TWINT))) // DS40002061B-p.222 The TWINT Flag is set after the TWI has transmitted data
	{}

	// // Display feedback status after data transmission
	// uart_display_status(TWSR & STATUS_MSK); // DS40002061B-p.222
}

void print_hex_value(char c)
{
	uart_tx_hex((uint8_t)c);
}

void i2c_read(void)
{
	uint8_t	length = 6;
	uint8_t	data[length];
	uint8_t ready = 0;

	while (!ready)
	{
		delay_ms(1);
		i2c_start();	
		i2c_send_address(AHT20_ADDR, 1);
		// uart_printstr("I2C SLA=AHT20+R Sent\r\n");

		for (uint8_t i = 0; i < length; i++)
		{
			if (i < length - 1)
				// ACK for all bytes except the last one
				TWCR = (1 << TWINT) | (1 << TWEN) | (1 << TWEA);
			else
				// NACK for the last byte — no TWEA
				TWCR = (1 << TWINT) | (1 << TWEN);

			// Wait for TWINT
			while (!(TWCR & (1 << TWINT)));

			// Store received data
			data[i] = TWDR;

			// // Display feedback status after data reception
			// uart_display_status(TWSR & STATUS_MSK);
		}
		i2c_stop();

		// Check busy bit — if still busy, loop and retry
		if (!(data[0] & AHT20_STATUS_BUSY))
			ready = 1;
	}

	/// Process the data
	// Extract humidity (20 bits: data[1] (8 bits) + data[2] (8 bits) + data[3] (4 bits))
	uint32_t humidity_raw = ((uint32_t)data[1] << 12) | ((uint32_t)data[2] << 4) | ((data[3] & 0xF0) >> 4);
	float humidity = (humidity_raw * 100.0) / 1048576.0;  // Convert to %

	// Extract temperature (20 bits: data[3] (4 bits) + data[4] (8 bits) + data[5] (8 bits))
	uint32_t temperature_raw = (((uint32_t)(data[3] & 0x0F)) << 16) | ((uint32_t)data[4] << 8) | data[5];
	float temperature = (temperature_raw * 200.0 / 1048576.0) - 50.0;  // Convert to Celsius

	// Store measurement in circular buffer of size 3
	g_measurements[g_measurement_index].temperature = temperature;
	g_measurements[g_measurement_index].humidity = humidity;
	g_measurement_index = (g_measurement_index + 1) % 3;

	// Calculate moving average of 3 values
	float avg_temp, avg_humidity;
	calculate_average(&avg_temp, &avg_humidity);

	// Round to nearest tenth
	avg_temp = round_to_one(avg_temp);
	avg_humidity = round_to_ten(avg_humidity);

	/// Display results
	uart_printstr("Temperature: ");
	uart_tx_dec_uint10((uint16_t)avg_temp);
	uart_printstr(".C, Humidity: ");
	uart_tx_dec_uint10((uint16_t)avg_humidity);
	uart_printstr("%\r\n");
}

void aht20_init_calibration(void)
{
	// Send START
	i2c_start();
	// uart_printstr("I2C START Sent\r\n");

	// Send address in write mode
	i2c_send_address(AHT20_ADDR, 0);
	// uart_printstr("I2C SLA=AHT20+W Sent\r\n");

	// Send calibration command for register 0x1B
	i2c_write(0x1B);
	i2c_write(0x00);
	i2c_write(0x00);
	uart_printstr("AHT20 Calibration Command Sent for register 0x1B\r\n");

	// Send STOP
	i2c_stop();
	// uart_printstr("I2C STOP Sent\r\n");

	// Wait
	delay_ms(20);

	// Send START
	i2c_start();
	// uart_printstr("I2C START Sent\r\n");

	// Send address in write mode
	i2c_send_address(AHT20_ADDR, 0);
	// uart_printstr("I2C SLA=AHT20+W Sent\r\n");

	// Send calibration command for register 0x1C
	i2c_write(0x1C);
	i2c_write(0x00);
	i2c_write(0x00);
	uart_printstr("AHT20 Calibration Command Sent for register 0x1C\r\n");

	// Send STOP
	i2c_stop();
	// uart_printstr("I2C STOP Sent\r\n");

	// Wait
	delay_ms(20);

	// Send START
	i2c_start();
	// uart_printstr("I2C START Sent\r\n");

	// Send address in write mode
	i2c_send_address(AHT20_ADDR, 0);
	// uart_printstr("I2C SLA=AHT20+W Sent\r\n");

	// Send calibration command for register 0x1E
	i2c_write(0x1E);
	i2c_write(0x00);
	i2c_write(0x00);
	uart_printstr("AHT20 Calibration Command Sent for register 0x1E\r\n");

	// Send STOP
	i2c_stop();
	// uart_printstr("I2C STOP Sent\r\n");

	// Wait for calibration to complete
	delay_ms(20);
}

uint8_t aht20_check_status(void)
{
	uint8_t status;

	// Send START
	i2c_start();
	// uart_printstr("I2C START Sent\r\n");

	// Send address in write mode
	i2c_send_address(AHT20_ADDR, 0);
	// uart_printstr("I2C SLA=AHT20+W Sent\r\n");

	// Send status check command (0x71)
	i2c_write(AHT20_STATUS_WORD_RQST);
	// uart_printstr("AHT20 Status Word Request Sent\r\n");

	i2c_stop();
	// uart_printstr("I2C STOP Sent\r\n");

	// Send START
	i2c_start();
	// uart_printstr("I2C START Sent\r\n");

	// Send address in read mode
	i2c_send_address(AHT20_ADDR, 1);
	// uart_printstr("I2C SLA=AHT20+R Sent\r\n");

	// Read status byte
	TWCR = (1 << TWINT) | (1 << TWEN) & ~(1 << TWEA);  // NACK (we only need 1 byte)
	while (!(TWCR & (1 << TWINT)));
	status = TWDR;

	// Send STOP
	i2c_stop();
	// uart_printstr("I2C STOP Sent\r\n");

	return (status);
}

void aht20_init(void)
{
	// Wait for power-on stabilization
	delay_ms(100); // AHT20 Data Sheet, Version:V1.0, p.13 (7.1 Start the sensor) / After power-on, the sensor needs ≥100ms time

	// Check status word
	uint8_t status = aht20_check_status();
	uart_printstr("AHT20 Status Reading = ");
	print_hex_value(status);
	uart_printstr("\r\n");

	if (status != AHT20_STATUS_WORD)
	{
		uart_printstr("AHT20 Status Meaning = Calibration needed\r\n");
		aht20_init_calibration();
		uart_printstr("AHT20 Calibrated\r\n");
	}
	uart_printstr("AHT20 Status Meaning = Ready\r\n");
}
	

int main(void)
{
	uart_init();
	uart_printstr("UART Initialized\r\n");
	init_timer_for_delay();
	uart_printstr("Timer Initialized\r\n");
	i2c_init();
	uart_printstr("I2C Initialized\r\n");
	aht20_init();
	uart_printstr("AHT20 Initialized\r\n");

	while (1)
	{
		i2c_start();
		// uart_printstr("I2C START Sent\r\n");
		i2c_send_address(AHT20_ADDR, 0);
		// uart_printstr("I2C SLA=AHT20+W Sent\r\n");
		i2c_write(AHT20_MEASUREMENT_CMD); // AHT20 Data Sheet, Version:V1.0, p.12 / Send trigger command (0xAC for normal mode for AHT20)	
		i2c_write(0x33); // AHT20 Data Sheet, Version:V1.0, p.12
		i2c_write(0x00); // AHT20 Data Sheet, Version:V1.0, p.12	
		i2c_stop();
		// uart_printstr("I2C STOP Sent\r\n");
		delay_ms(80); // AHT20 Data Sheet, Version:V1.0, p.13 / delay more than 80 milliseconds before reading the converted data
		// uart_printstr("Delay 80ms\r\n");
		i2c_read();
		delay_ms(10); // AHT20 Data Sheet, Version:V1.0, p.12 Wait 10ms to send the 0xAC command
	}
}
